### ISSUE TITLE
Do I get this error help?

### ISSUE THREAD

**Issue by onrsz15** [leonidg/Poor-Man-s-traceroute#2]
Exception has occurred: TypeError
error() missing 1 required positional argument: 'msg'
File "C:\Users\ONUR\Desktop\Poor-Man-s-traceroute-master\Poor-Man-s-traceroute-master\traceroute.py", line 66, in 
parser.error()

**Comment by leonidg** [comment]
It looks like you're not passing the argument.  The way to run the program is

```
python traceroute.py hostname
```

For example,

```
python traceroute.py google.com
```
